$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: diabetes_deployment
endpoint_name: diabetes
model:
  name: diabetes_model
  version: '@latest'
  path: azureml://locations/eastus/workspaces/84b4a7e0-f198-4cfd-980e-be9ba1456df9/models
  type: mlflow_model
instance_type: Standard_F4s_v2
instance_count: 1
