name: basic-env-cpu
channels:
  - conda-forge
dependencies:
  - python=3.12
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - pip
  - pip:
    - azureml-defaults
    - azureml-core
    - azureml-mlflow
    - mlflow
