name: Train Model
on:
  push:
    branches:
      - main

jobs:
        experiment:
          runs-on: ubuntu-latest
          environment: development
          steps:
          - name: Check out repo
            uses: actions/checkout@v2
          - name: Install az ml extension
            run: az extension add -n ml -y
          - name: Azure login
            uses: azure/login@v1
            with:
              creds: ${{secrets.AZURE_CREDENTIALS}}
          - name: Submit a train job
            run: |
                az ml job create --file Initial_job/train_dev.yml --name train-dev --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev --stream
          - name: Save trained model
            run: |
                 # Download the model from the job's outputs
                 az ml job download --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev --name train-dev --output-path ./outputs
          - name: Upload model as artifact
            uses: actions/upload-artifact@v2
            with:
              name: model
              path: ./outputs/model/model.pkl
      
        production:
          needs: experiment
          runs-on: ubuntu-latest
          environment: production
          steps:
          - name: Check out repo
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: pip install -r requirements.txt
          - name: Download model artifact
            uses: actions/download-artifact@v2
            with:
              name: model
              path: ./outputs
          - name: Retrain model
            run: |
             echo "Retraining model"
               az ml job create --file /workspaces/MLops-exercise/retrain_model/retrain_model.yml --name retrain-model --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev --stream 
          - name: Save retrained model
            run: |
                 # Download the model from the job's outputs
                 az ml job download --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev --name retrain-model --output-path ./outputs

          
