name: Train Model
on:
  push:
    branches:
      - main
env:
  DEV_AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  PROD_AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
jobs:
  production:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ env.PROD_AZURE_CREDENTIALS }}
    - name: Retrain model
      id: retrain
      run: |
           echo "Retraining model"
           job_name="retrain-model-$(date +%Y%m%d%H%M%S)"
           echo "JOB_NAME=$job_name" >> $GITHUB_ENV
           az ml job create --file retrain_model/retrain_model.yml --name $job_name --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev --stream 

    - name: Register model
      run: |
        model_name="diabetes_model"
        model_path="azureml://jobs/$JOB_NAME/outputs/artifacts/model"
        az ml model create --name $model_name --type "mlflow_model" --path $model_path --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev
   
    - name: Deploy model to online endpoint
      run: |
        deployment_name="diabetes_deployment"
        model_name="diabetes_model"
        az ml online-deployment create --name $deployment_name --endpoint diabetes --model ${model_name}@latest --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev
