name: pull-request-workflow
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          echo "Dependencies installe d"
      - name: Run unit tests
        run: pytest tests/
