name: pull-request-workflow

on:
    push:
      branches:
        - main

jobs:
    check-pullrequest:
        runs-on: ubuntu-latest
        steps:
        - name: Placeholder
          run: |
            echo "Will add code checks here in next challenge!"
          




